### PR TITLE
fix-issue-164: Fix for shortcut 'move up/down'

### LINKED ISSUE #164: Shortcut 'move up/down' is not working
The shortcut for moving a row in a table up/down is broken.

### PR DESCRIPTION
**Pull request by zzacharo**
(Closes #164)

Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

### CODE REVIEW

File: src/primitive-field/primitive-field.component.ts [hunk 1]
```diff
@@ -110,11 +106,11 @@ export class PrimitiveFieldComponent extends AbstractFieldComponent implements O
     return this.schema['x_editor_link_builder'];
   }
 
-  getTabIndex(): number {
+  get tabIndex(): number {
     return this.tabIndexService.getElemTabIndex(this.path.join('.'));
```
Comment (harunurhan) [inline src/primitive-field/primitive-field.component.ts]: `this.pathString` instead of `this.path.join('.')`

File: src/primitive-field/primitive-field.component.ts [hunk 2]
```diff
@@ -110,11 +106,11 @@ export class PrimitiveFieldComponent extends AbstractFieldComponent implements O
...
   }
 
   setTabIndex() {
-    this.tabIndex = this.tabIndexService.addElemTabIndex(this.path.join('.'));
+    this.tabIndexService.addElemTabIndex(this.path.join('.'));
```
Comment (harunurhan) [inline src/primitive-field/primitive-field.component.ts]: ditto

File: src/shared/services/shortcut-action.service.ts [hunk 3]
```diff
@@ -215,6 +215,12 @@ export class ShortcutActionService {
     this.domUtilService.focusAndSelectFirstInputChildById(path);
   }
 
+  private clearFocus(path: string) {
```
Comment (harunurhan) [inline src/shared/services/shortcut-action.service.ts]: move to dom-utils service, name it `blurFirstInputChildById`. Also it would be nice if you write in multiple lines, 
```
let el = doc...byId(..);
let firstInput = el.querySelector(...) as HTMLInputElement;
firstInput.blur();

File: src/primitive-field/primitive-field.component.ts (hunk 1 above)
Comment (zzacharo) [inline src/primitive-field/primitive-field.component.ts]: `this.pathString` ? You mean to assign it first into a variable?

**Comment by zzacharo** [comment]
@harunurhan check again!

File: src/shared/services/dom-util.service.ts [hunk 4]
```diff
@@ -74,4 +74,12 @@ export class DomUtilService {
       }, 500);
     }
   }
+
+  blurFirstInputChildById(path: string) {
```
Comment (harunurhan) [inline src/shared/services/dom-util.service.ts]: `id` instead of `path`

File: src/shared/services/shortcut-action.service.ts [hunk 5]
```diff
@@ -80,12 +80,14 @@ export class ShortcutActionService {
    * @param {number} direction - Movement direction. -1 for UP, +1 for DOWN
    */
   private move(path: Array<any>, direction: number): void {
+    this.domUtilService.blurFirstInputChildById(path.join('.'));
     let index = this.pathUtilService.getElementIndexInForwardOrReversePath(path, false);
     path[path.length - 2] = this.moveElement(index, direction, this.pathUtilService.getNearestOrRootArrayParentInPath(path, false));
     let pathString = path.join('.');
```
Comment (harunurhan) [inline src/shared/services/shortcut-action.service.ts]: can you do this before the https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/165/files#diff-0da253bfd51f517c1804433a90ad5351R83 so that we don't `join` twice.

Comment (zzacharo) [inline src/shared/services/shortcut-action.service.ts]: The second join is in the modified path. So I need the initial path to blur.

**Comment by harunurhan** [comment]
@zzacharo everything else looks good but can you add a e2e that covers the case in the issue.

**Comment by zzacharo** [comment]
@harunurhan I included some modifications on existing tests  for these issues. You can see the commnents in the code here https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/165/files#diff-5a31329b1c08e4b38445f4db7d5b13aeR70 and https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/165/files#diff-5a31329b1c08e4b38445f4db7d5b13aeR80

**Comment by zzacharo** [comment]
Is anything else with this PR to be merged?

**Comment by zzacharo** [comment]
@harunurhan @jmartinm Check again this PR!

File: e2e/shortcut-action/shortcut-action.e2e-spec.ts [hunk 6]
```diff
@@ -58,19 +58,29 @@ describe('Shortcut-action App', function() {
   });
 
   it(`should move row up using 'mod+shift+up' shortcut`, () => {
-    let inputElem = page.getChildOfElementByCss(page.getElementById('accelerator_experiments.1.experiment'), 'textarea');
-    let inputElemValue = inputElem.getAttribute('value');
-    inputElem.sendKeys(protractor.Key.chord(mod, protractor.Key.SHIFT, protractor.Key.UP));
-    let movedUpInputElem = page.getChildOfElementByCss(page.getElementById('accelerator_experiments.0.experiment'), 'textarea');
-    expect(movedUpInputElem.getAttribute('value')).toEqual(inputElemValue);
+    let currentFirstRow = page.getElementArrayById('accelerator_experiments.0');
```
Comment (jmartinm) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: since `getElementArrayById ` returns a promise, what are comparing below?

Comment (zzacharo) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: The array with the elements of the first row. The `toEqual()` is waiting for the promises to be resolves an then it compares their values.

**Comment by jmartinm** [comment]
It seems like Travis did not run for the latest version of the PR?

**Comment by zzacharo** [comment]
https://travis-ci.org/inveniosoftware-contrib/ng2-json-editor/jobs/196976037#L460 is this error only on me? I rebased with master.

**Comment by jmartinm** [comment]
I have not seen that error before, maybe @harunurhan has some more info.

File: src/primitive-field/primitive-field.component.ts [hunk 7]
```diff
@@ -106,11 +102,15 @@ export class PrimitiveFieldComponent extends AbstractFieldComponent implements O
     this.commitValueChange();
   }
 
-  getTabIndex(): number {
-    return this.tabIndexService.getElemTabIndex(this.path.join('.'));
+  get linkBuilder(): LinkBuilderFunction {
```
Comment (harunurhan) [inline src/primitive-field/primitive-field.component.ts]: You're getting travis error because you haven't rebased, also this part is unrelated and actually is part of another PR.

@zzacharo

Comment (zzacharo) [inline src/primitive-field/primitive-field.component.ts]: I am sure that I rebases with master. But if this is part of another PR how I got a conflict with it? I mean it's strange...Anyway I will remove this tomorrow and push again.

File: e2e/shortcut-action/shortcut-action.e2e-spec.ts [hunk 8]
```diff
@@ -58,19 +58,29 @@ describe('Shortcut-action App', function() {
...
+    expect(targetSecondRow).not.toEqual(targetFirstRow);
   });
 
   it(`should move row down using 'mod+shift+down' shortcut`, () => {
-    let inputElem = page.getChildOfElementByCss(page.getElementById('accelerator_experiments.0.experiment'), 'textarea');
-    let inputElemValue = inputElem.getAttribute('value');
-    inputElem.sendKeys(protractor.Key.chord(mod, protractor.Key.SHIFT, protractor.Key.DOWN));
-    let movedDownInputElem = page.getChildOfElementByCss(page.getElementById('accelerator_experiments.1.experiment'), 'textarea');
-    expect(movedDownInputElem.getAttribute('value')).toEqual(inputElemValue);
+   let currentRow = page.getElementArrayById('accelerator_experiments.0');
```
Comment (zzacharo) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: @jmartinm @harunurhan This is the helper function returning the row of elements by a specifc id. Any comments on this? I will update the PR to pass the build and just comment if we want something else to change.

**Comment by zzacharo** [comment]
@harunurhan Check again!

File: e2e/shortcut-action/shortcut-action.po.ts [hunk 9]
```diff
@@ -49,4 +53,34 @@ export class ShortcutActionPage extends Ng2JsonEditorPage {
     let elem = element(by.id(id));
     return elem.all(by.css('input')).count();
   }
+
+  getElementArrayById(id: string) {
+    let elems = this.getChildrenOfElementByCss(this.getElementById(id), 'textarea,input,a');
+    let deferred = protractor.promise.defer();
+    let returnArray = [];
+    elems
+      .map(elem => {
```
Comment (jmartinm) [inline e2e/shortcut-action/shortcut-action.po.ts]: Here `each` would be better.

**Comment by zzacharo** [comment]
@jmartinm I changed it! But probably because I transfor each element and return finally the modified array `map` wasn't so bad...

File: e2e/shortcut-action/shortcut-action.po.ts [hunk 10]
```diff
@@ -36,10 +36,14 @@ export class ShortcutActionPage extends Ng2JsonEditorPage {
...
-  getChildOfElementByCss(elem: ElementFinder, css: string) {
+  getChildOfElementByCss(elem: ElementFinder, css: string): ElementFinder {
     return elem.element(by.css(css));
   }
 
+  getChildrenOfElementByCss(elem: ElementFinder, css: string): ElementArrayFinder {
+    return elem.all((by.css(css)));
+  }
+
   getNumberOfTextareaElementsById(id: string) {
```
Comment (harunurhan) [inline e2e/shortcut-action/shortcut-action.po.ts]: return type (although not part of this PR, still would be nice to have)

File: e2e/shortcut-action/shortcut-action.po.ts [hunk 11]
```diff
@@ -49,4 +53,12 @@ export class ShortcutActionPage extends Ng2JsonEditorPage {
     let elem = element(by.id(id));
     return elem.all(by.css('input')).count();
   }
+
+  getElementArrayById(id: string) {
```
Comment (harunurhan) [inline e2e/shortcut-action/shortcut-action.po.ts]: return type

File: e2e/shortcut-action/shortcut-action.po.ts [hunk 12]
```diff
@@ -20,13 +20,13 @@
...
-import { element, by } from 'protractor/globals';
+import { element, by, protractor } from 'protractor/globals';
 import { Ng2JsonEditorPage } from '../app.po';
-import {ElementFinder} from 'protractor';
+import { ElementFinder, ElementArrayFinder } from 'protractor';
 
 export class ShortcutActionPage extends Ng2JsonEditorPage {
 
-  getNumberOfChildRowsbyId(id: string) {
+  getNumberOfChildRowsbyId(id: string): webdriver.promise.Promise<number> {
```
Comment (harunurhan) [inline e2e/shortcut-action/shortcut-action.po.ts]: can we have shorthand for `webdriver.promise.Promise<T>` like `export type WDPromise<T> = webdriver.promise.Promise<T>`. Use it if it works, don't worry if it doesn't.

File: e2e/shortcut-action/shortcut-action.po.ts (hunk 11 above)
Comment (harunurhan) [inline e2e/shortcut-action/shortcut-action.po.ts]: AFAI understand from the code, it returns values of children inputs. So maybe a more descriptive name like `getValueOfChildrenById`.

File: src/shared/services/dom-util.service.ts [hunk 13]
```diff
@@ -74,4 +74,12 @@ export class DomUtilService {
       }, 500);
     }
   }
+
+  blurFirstInputChildById(id: string) {
+    let el = document.getElementById(id);
+    let firstInput = el.querySelector('input,textarea') as HTMLInputElement;
```
Comment (harunurhan) [inline src/shared/services/dom-util.service.ts]: Minor styling: `input, textarea` with a space after comma.

**Comment by zzacharo** [comment]
@harunurhan Check it again!

File: e2e/app.po.ts [hunk 14]
```diff
@@ -32,3 +32,5 @@ export class Ng2JsonEditorPage {
     return element(by.id(id));
   }
 }
+
+export type Webdriver<T> = webdriver.promise.Promise<T>;
```
Comment (harunurhan) [inline e2e/app.po.ts]: `WDPromise<T>` to be understand that the type is actually some kind of Promise implementation.

**Comment by harunurhan** [comment]
LGTM, but should we have tests for the second commit case? @jmartinm

**Comment by harunurhan** [comment]
LGTM @jmartinm, you can have a final look and merge.

File: e2e/shortcut-action/shortcut-action.e2e-spec.ts [hunk 15]
```diff
@@ -58,19 +58,39 @@ describe('ShortcutAction', function() {
...
+   currentElem.sendKeys(protractor.Key.chord(mod, protractor.Key.SHIFT, protractor.Key.DOWN));
+   currentElem = page.getChildOfElementByCss(page.getElementById('keywords.1.keyword'), 'textarea');
+   // Trigger move down shortcut two time in a row to test issue of not updating tabindexes correctly on sequential
+   // trigger of the shortcut. As a result the shortcut was not working properly.
+   currentElem.sendKeys(protractor.Key.chord(mod, protractor.Key.SHIFT, protractor.Key.DOWN));
+   let targetRow = page.getValuesOfChildrenById('keywords.2');
+   expect(targetRow).toEqual(currentRow);
+  });
+
+  it(`should update tabindexes correctly of the switched rows when moving up/down clicking the button`, () => {
```
Comment (jmartinm) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: This test is only checking the up button, so description saying up/down is not correct.

Can you add another test for the down button?

File: ng2-json-editor.d.ts [hunk 16]
```diff
@@ -0,0 +1 @@
+export * from './dist';
```
Comment (harunurhan) [inline ng2-json-editor.d.ts]: shouldn't be here

File: ng2-json-editor.js [hunk 17]
```diff
@@ -0,0 +1 @@
+export * from './dist';
```
Comment (harunurhan) [inline ng2-json-editor.js]: shouldn't be here

File: e2e/shortcut-action/shortcut-action.e2e-spec.ts [hunk 18]
```diff
@@ -58,19 +58,39 @@ describe('ShortcutAction', function() {
...
+    let currentRowElem = page.getChildOfElementByCss(page.getElementById('accelerator_experiments.0.experiment'), 'textarea');
+    page.getChildOfElementByCss( page.getElementById('accelerator_experiments.1'), '.editor-btn-move-up').click();
+    let targetRowElem = page
```
Comment (jmartinm) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: There is something quite confusing about this naming, your `currentRowElem` is the element 0 but then you take the action of click in element 1. (in the other tests `current` means the one you are going to do an action)

Then there is `targetRowElem` which is element 1. But if you click `up` on element 1 your target would be element 0 for better naming.

And then finally before the assertion, the comment says:

```
// moved element's tabindex must have increased by 1
```

but inside you check `targetTabIndex  - 1 == currentRowTabIndex`. Since you clicked the up button I would expect that that the `targetTabIndex  + 1 == currentRowTabIndex` if target was the element 0.

File: e2e/shortcut-action/shortcut-action.e2e-spec.ts [hunk 19]
```diff
@@ -86,18 +106,19 @@ describe('ShortcutAction', function() {
...
-      .getAttribute('value');
-    firstColInputElem.sendKeys(protractor.Key.chord(protractor.Key.ALT, 'c'));
-    let firstColAfterCopyInputElemValue = page
-      .getChildOfElementByCss(page.getElementById('keywords.1.classification_scheme'), 'textarea')
-      .getAttribute('value');
-    let secondColAfterCopyInputElemValue = page.getChildOfElementByCss(page.getElementById('keywords.1.keyword'), 'textarea')
-      .getAttribute('value');
-    expect(firstColAfterCopyInputElemValue).toEqual('');
-    expect(secondColAfterCopyInputElemValue).toEqual(secondColInputElemValue);
+    let currentRowPromise = page.getValuesOfChildrenById('keywords.0');
```
Comment (jmartinm) [inline e2e/shortcut-action/shortcut-action.e2e-spec.ts]: `currentRowPromise` is a good name since a promise is returned. On the other hand, only this test uses that naming convention, can you update the other ones to use the same naming?
